### ISSUE TITLE
Carry out TODO

### ISSUE THREAD

**Issue by JJ** [rubensworks/rdf-string.js#28] opened 2022-05-17 10:42 UTC
That nasty bug has already been quashed, apparently.

https://github.com/rubensworks/rdf-string.js/blob/64979e9e443497a4e8f266e386d4373e929d0b3f/lib/TermUtil.ts#L25

**Comment by snoack** [comment] 2022-05-18 16:54
Duplicate of #23?

**Comment by rubensworks** [comment] 2022-05-18 16:56
Yes indeed, I even forgot that issue existed :-)

**Closed by rubensworks** 2022-05-18 16:56 UTC
